apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-back-certificado
  namespace: infra-ns
spec:
  secretName: minio-back-tls-secret # Nome do segredo onde o certificado será armazenado
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: minioback.deinfra.sc.gov.br
  dnsNames:
    - minioback.deinfra.sc.gov.br
