# minio-config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
  namespace: integra-glpi-ns
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="Sie@2025"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque

---
# minio-user-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: integra-glpi-ns
type: Opaque
data:
  CONSOLE_ACCESS_KEY: bWluaW8= # "minio" em base64
  CONSOLE_SECRET_KEY: U2llQDIwMjU= # "Sie@2025" em base64
