apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: my-user
  namespace: rook-ceph
spec:
  store: my-store # Nome do CephObjectStore criado anteriormente
  displayName: "My S3 User"
