apiVersion: v1
kind: Pod
metadata:
  name: my-pod-teste
  namespace: rook-ceph
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - mountPath: "/mnt/cephfs"
          name: cephfs-storage
  volumes:
    - name: cephfs-storage
      persistentVolumeClaim:
        claimName: ceph-nfs-pvc
